# Generated by Django 5.2.16 on 2026-07-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
