# Generated by Django 5.2.16 on 2026-08-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'платёж', 'verbose_name_plural': 'платежи'},
        ),
    ]
