# Generated by Django 5.2.16 on 2026-08-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["id"]},
        ),
    ]
