# Generated by Django 5.2.17 on 2026-08-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней рассылки'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
